feat(prefer-in-document): add support for assigments
testing-library/eslint-plugin-jest-dom pull request #107
Opened 2020-11-27 23:24 UTC by benmonro

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [ ] Ready to be merged

2020-11-28 19:17 UTC, benmonro commented on src/__tests__/lib/rules/prefer-in-document.js
> +      `expect(${q}('foo')) .not .toBeNull()`,
@AntonNiklasson FYI i had to change around the fixer from what you had due to this use case here.  FYI using hard coded numbers in a fixer can be problematic for stuff like spacing etc.

2020-11-29 10:23 UTC, AntonNiklasson requested changes
I ran this code on one of our codebases to validate, and it crashed. This case seems to be reproducing it:

```diff
diff --git a/src/__tests__/lib/rules/prefer-in-document.js b/src/__tests__/lib/rules/prefer-in-document.js
index 376dfda..bc0faf1 100644
--- a/src/__tests__/lib/rules/prefer-in-document.js
+++ b/src/__tests__/lib/rules/prefer-in-document.js
@@ -91,6 +91,12 @@ const invalid = [
       foo = screen.${q}('foo');
       expect(foo).toBeInTheDocument();`
     ),
+    invalidCase(
+      `const compressingFeedback = await screen.findByText(/Compressing video/);
+      expect(compressingFeedback).toBeDefined();`,
+      `const compressingFeedback = await screen.findByText(/Compressing video/);
+      expect(compressingFeedback).toBeInTheDocument();`
+    ),
   ]),
   // Invalid cases that applies to queryBy* and queryAllBy*
   ...queriesByVariant.query.map((q) => [
```

2020-11-30 18:06 UTC, AntonNiklasson requested changes
Looking good! I played around with the latest changes and managed to find another test case that currently crashes:

```
invalidCase(
  `let button;
  it("foo", async () => {
    button = await screen.findByText('click me');
    expect(button).toBeDefined();
  });`,
  `let button;
  it("foo", async () => {
    button = await screen.findByText('click me');
    expect(button).toBeInTheDocument();
  });`
)
```

I do think this "pattern" is fairly common, but it's not really feasible for this rule to support be 100% with this. I just felt that this case was pretty similar to what you already had there.

2020-11-30 21:32 UTC, benmonro commented on docs/rules/prefer-in-document.md
>  expect(screen.queryByText("foo")).toBeInTheDocument();
```suggestion
expect(await screen.findByText("foo")).toBeInTheDocument();
```

2020-11-30 21:34 UTC, benmonro commented on docs/rules/prefer-in-document.md
> +expect(bar).not.toBeInTheDocument();
```suggestion
expect(bar).not.toBeDefined();

const baz = await screen.findByText("baz");
expect(baz).toBeDefined()
```

2020-11-30 21:36 UTC, nickmccurdy commented
This isn't a code review, but FWIW this fixes the errors in https://github.com/testing-library/dom-testing-library/pull/834. Nice work!

2020-11-30 21:44 UTC, merged

2020-11-30 22:05 UTC, nickmccurdy commented
We're getting various runtime failures in dom-testing-library after upgrading and linting with `--fix`. It seems like it replaces some array assertions where it shouldn't, among other things.

2020-11-30 22:07 UTC, benmonro commented
oy.  got any examples?

2020-11-30 22:09 UTC, nickmccurdy commented
Do you want me to just publish a branch so you can see the CI build?

2020-11-30 22:10 UTC, benmonro commented
that would be excellent, thanks @nickmccurdy

2020-11-30 22:21 UTC, nickmccurdy commented
https://github.com/testing-library/dom-testing-library/pull/839/checks?check_run_id=1476727442

2020-11-30 22:24 UTC, benmonro commented
@nickmccurdy looks liek those are coming from usages of `getAllBy` that should actually be using `getBy`, no?  Would it maybe make more sense to update those?