fix(getQueryNodeFrom): move checks for Identifier type to getInnerNodeFrom
testing-library/eslint-plugin-jest-dom pull request #255
Opened 2022-01-21 23:15 UTC by ricardozv28

**What**: 
Move logic for checking if expression type is Identifier to getInnerNodeFrom method

**Why**:
As reported on issue #203, features like `.toBeDisabled()` are not getting recommend as fixes for code like the following:
```js
const button = getByRole('button', { name: 'My Button' });
expect(button.disabled).toBe(true);
```

**How**:
After a little bit of digging, I noticed that when using `getByRole` method the type of the expression that was getting passed to getInnerNodeFrom was a `MemberExpression`, which was being handled by in the switch statement, `expression.object` was getting passed now to getInnerNodeFrom which was the type of 'Identifier' but since that case is not getting handled in the method and the returned expression didn't have a property `.callee` which was making `getQueryNodeFrom`  to return `isDTLQuery` as false

**Checklist**:

- [ ] Documentation
- [ ] Tests
- [x] Ready to be merged
      

Fix #203

2022-11-24 19:56 UTC, G-Rath requested changes
Can you add a few test cases please?

2023-01-13 04:35 UTC, ricardozv28 commented
> Can you add a few test cases please?

trying to pick this up again in my free time, do you have some existing unit test examples that I can take a look at for reference??

2023-01-14 17:53 UTC, G-Rath commented
@ricardozv28 tests for rules live [here](https://github.com/testing-library/eslint-plugin-jest-dom/tree/main/src/__tests__/lib/rules) - you don't need to add tests to every rule, but we should have a couple if possible (including one [here](https://github.com/testing-library/eslint-plugin-jest-dom/blob/main/src/__tests__/lib/rules/no-attribute-checking.js) for `toBeDisabled`)

2023-06-04 19:03 UTC, G-Rath approved these changes

2023-06-04 19:40 UTC, MichaelDeBoey approved these changes

2023-06-04 19:41 UTC, merged